
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apltkougkglbsfphbghi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbHRrb3Vna2dsYnNmcGhiZ2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTE3MDMsImV4cCI6MjA1OTE2NzcwM30.Kk38S9Hl9tIwv_a3VPgUaq1cSCCPmlGJOR5R98tREeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'x-application-name': 'cuephoria'
    }
  }
});

// Helper function to log and format errors from Supabase
export const handleSupabaseError = (error: any, operation: string): string => {
  console.error(`Supabase ${operation} error:`, error);
  
  // Format the error message
  if (error.code === '23505') {
    return 'This item already exists. Please try another one.';
  } else if (error.code === '23503') {
    return 'This operation references an item that doesn\'t exist.';
  } else if (error.code === '42P01') {
    return 'Database table not found. Please contact support.';
  } else if (error.message) {
    return error.message;
  } else {
    return `Error during ${operation}. Please try again.`;
  }
};

// Helper functions for data conversion
export const convertFromSupabaseProduct = (item: any): any => {
  const product = {
    id: item.id,
    name: item.name,
    price: item.price,
    category: item.category,
    stock: item.stock,
    image: item.image || undefined,
    originalPrice: item.original_price || undefined,
    offerPrice: item.offer_price || undefined,
    studentPrice: item.student_price || undefined,
    duration: item.duration || undefined,
    membershipHours: item.membership_hours || undefined
  };
  
  console.log('Converted product from DB:', product);
  return product;
};

export const convertToSupabaseProduct = (product: any): any => {
  const supabaseProduct = {
    id: product.id,
    name: product.name,
    price: product.price,
    category: product.category,
    stock: product.stock,
    image: product.image,
    original_price: product.originalPrice,
    offer_price: product.offerPrice,
    student_price: product.studentPrice,
    duration: product.duration,
    membership_hours: product.membershipHours
  };
  
  console.log('Converting product to Supabase format:', supabaseProduct);
  return supabaseProduct;
};
